CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    last_name varchar(255) NOT NULL,
    birth_date date,
    cpf varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    zip_code varchar(255) NOT NULL,
    plan varchar(255) NOT NULL
);
CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category varchar(255) NOT NULL
);
CREATE TABLE sectors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    type varchar(255) NOT NULL
);
CREATE TABLE products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand varchar(255) NOT NULL,
    price numeric(12,2) NOT NULL,
    name varchar(100) NOT NULL UNIQUE,
    category_id bigint NOT NULL REFERENCES categories(id)
);
CREATE TABLE customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id bigint NOT NULL UNIQUE REFERENCES users(id)
);
CREATE TABLE employees (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position varchar(255) NOT NULL,
    users_id bigint NOT NULL UNIQUE REFERENCES users(id)
);
